language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm test:unit
  - npm run build
deploy:
  provider: surge
  skip_cleanup: true
  domain: pizza-ovens.surge.sh
  project: ./dist/
on:
  branch: master